[2023-01-20T16:46:30.953+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T16:46:30.967+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T16:46:30.967+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T16:46:30.968+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-20T16:46:30.968+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T16:46:30.982+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-20T16:46:30.992+0000] {standard_task_runner.py:55} INFO - Started process 1932 to run task
[2023-01-20T16:46:30.998+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp9gvy_878']
[2023-01-20T16:46:31.004+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask transform_stage_generation
[2023-01-20T16:46:31.116+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 5efae2a07872
[2023-01-20T16:46:31.233+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-20T16:46:31.249+0000] {spark_submit.py:222} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-01-20T16:46:31.251+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master yarn --jars /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/gcs-connector-hadoop3-latest.jar, /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-20T16:46:31.261+0000] {spark_submit.py:495} INFO - /usr/local/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-submit: line 27: /opt/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-class: No such file or directory
[2023-01-20T16:46:31.274+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --jars /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/gcs-connector-hadoop3-latest.jar, /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 127.
[2023-01-20T16:46:31.280+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230120T164630, end_date=20230120T164631
[2023-01-20T16:46:31.297+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 81 for task transform_stage_generation (Cannot execute: spark-submit --master yarn --jars /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/gcs-connector-hadoop3-latest.jar, /opt/spark-3.3.1-bin-hadoop3-scala2.13/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 127.; 1932)
[2023-01-20T16:46:31.330+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T16:46:31.356+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-20T18:52:44.805+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T18:52:44.858+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T18:52:44.860+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T18:52:44.861+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-20T18:52:44.862+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T18:52:44.914+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-20T18:52:44.945+0000] {standard_task_runner.py:55} INFO - Started process 80 to run task
[2023-01-20T18:52:44.961+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp1o4d1m39']
[2023-01-20T18:52:44.971+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask transform_stage_generation
[2023-01-20T18:52:45.243+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 117f9fff6b95
[2023-01-20T18:52:45.556+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-20T18:52:45.558+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 165, in _get_hook
    return SparkSubmitHook(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 155, in __init__
    raise RuntimeError(
RuntimeError: The spark-binary extra can be on of ['spark-submit', 'spark2-submit'] and it was `/opt/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH
[2023-01-20T18:52:45.600+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230120T185244, end_date=20230120T185245
[2023-01-20T18:52:45.668+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 121 for task transform_stage_generation (The spark-binary extra can be on of ['spark-submit', 'spark2-submit'] and it was `/opt/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH; 80)
[2023-01-20T18:52:45.755+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T18:52:45.925+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-20T19:31:03.454+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T19:31:03.465+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-20T19:31:03.465+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T19:31:03.465+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-20T19:31:03.465+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T19:31:03.478+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-20T19:31:03.491+0000] {standard_task_runner.py:55} INFO - Started process 1293 to run task
[2023-01-20T19:31:03.496+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp54vxnc5m']
[2023-01-20T19:31:03.500+0000] {standard_task_runner.py:83} INFO - Job 135: Subtask transform_stage_generation
[2023-01-20T19:31:03.576+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 984f5901aea4
[2023-01-20T19:31:03.656+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-20T19:31:03.657+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 165, in _get_hook
    return SparkSubmitHook(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 155, in __init__
    raise RuntimeError(
RuntimeError: The spark-binary extra can be on of ['spark-submit', 'spark2-submit'] and it was `/usr/local/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH
[2023-01-20T19:31:03.668+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230120T193103, end_date=20230120T193103
[2023-01-20T19:31:03.683+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 135 for task transform_stage_generation (The spark-binary extra can be on of ['spark-submit', 'spark2-submit'] and it was `/usr/local/spark-3.3.1-bin-hadoop3-scala2.13/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH; 1293)
[2023-01-20T19:31:03.708+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T19:31:03.732+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T07:36:17.667+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T07:36:17.686+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T07:36:17.687+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T07:36:17.687+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T07:36:17.687+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T07:36:17.706+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T07:36:17.721+0000] {standard_task_runner.py:55} INFO - Started process 448 to run task
[2023-01-21T07:36:17.728+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpb7jur_a_']
[2023-01-21T07:36:17.733+0000] {standard_task_runner.py:83} INFO - Job 148: Subtask transform_stage_generation
[2023-01-21T07:36:17.840+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 2b3134e2b02d
[2023-01-21T07:36:17.949+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T07:36:17.951+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-21T07:36:17.953+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T07:36:17.969+0000] {spark_submit.py:495} INFO - /usr/local/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T07:36:22.826+0000] {spark_submit.py:495} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2023-01-21T07:36:22.826+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:975)
[2023-01-21T07:36:22.827+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
[2023-01-21T07:36:22.827+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2023-01-21T07:36:22.827+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2023-01-21T07:36:22.827+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2023-01-21T07:36:22.827+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2023-01-21T07:36:22.828+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2023-01-21T07:36:22.828+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2023-01-21T07:36:22.828+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-01-21T07:36:22.879+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T07:36:22.887+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T073617, end_date=20230121T073622
[2023-01-21T07:36:22.914+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 148 for task transform_stage_generation (Cannot execute: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 448)
[2023-01-21T07:36:22.952+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T07:36:22.982+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T08:02:59.040+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T08:02:59.052+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T08:02:59.052+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T08:02:59.052+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T08:02:59.052+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T08:02:59.067+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T08:02:59.078+0000] {standard_task_runner.py:55} INFO - Started process 1311 to run task
[2023-01-21T08:02:59.084+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpfilcott1']
[2023-01-21T08:02:59.088+0000] {standard_task_runner.py:83} INFO - Job 168: Subtask transform_stage_generation
[2023-01-21T08:02:59.171+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4d52b49e46b4
[2023-01-21T08:02:59.266+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T08:02:59.268+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-21T08:02:59.271+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T08:02:59.286+0000] {spark_submit.py:495} INFO - /usr/local/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T08:03:02.139+0000] {spark_submit.py:495} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2023-01-21T08:03:02.139+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:975)
[2023-01-21T08:03:02.139+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
[2023-01-21T08:03:02.139+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2023-01-21T08:03:02.140+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-01-21T08:03:02.174+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T08:03:02.179+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T080259, end_date=20230121T080302
[2023-01-21T08:03:02.195+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 168 for task transform_stage_generation (Cannot execute: spark-submit --master  --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 1311)
[2023-01-21T08:03:02.213+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T08:03:02.235+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T08:39:09.790+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T08:39:09.799+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T08:39:09.800+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T08:39:09.800+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T08:39:09.800+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T08:39:09.809+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T08:39:09.815+0000] {standard_task_runner.py:55} INFO - Started process 1646 to run task
[2023-01-21T08:39:09.818+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpuf5fe9oz']
[2023-01-21T08:39:09.820+0000] {standard_task_runner.py:83} INFO - Job 186: Subtask transform_stage_generation
[2023-01-21T08:39:09.868+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host d00464a30031
[2023-01-21T08:39:09.933+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T08:39:09.944+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T08:39:09.947+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T08:39:10.008+0000] {spark_submit.py:495} INFO - /usr/local/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T08:39:12.171+0000] {spark_submit.py:495} INFO - 23/01/21 08:39:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T08:39:12.389+0000] {spark_submit.py:495} INFO - 23/01/21 08:39:12 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T08:39:12.492+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-21T08:39:12.492+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 2, in <module>
[2023-01-21T08:39:12.492+0000] {spark_submit.py:495} INFO - from dotenv import load_dotenv
[2023-01-21T08:39:12.492+0000] {spark_submit.py:495} INFO - ModuleNotFoundError: No module named 'dotenv'
[2023-01-21T08:39:12.501+0000] {spark_submit.py:495} INFO - 23/01/21 08:39:12 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T08:39:12.502+0000] {spark_submit.py:495} INFO - 23/01/21 08:39:12 INFO ShutdownHookManager: Deleting directory /tmp/spark-3c7cad4e-6d9c-43bc-a10f-9c22671c0fd4
[2023-01-21T08:39:12.550+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T08:39:12.552+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T083909, end_date=20230121T083912
[2023-01-21T08:39:12.561+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 186 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 1646)
[2023-01-21T08:39:12.581+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T08:39:12.594+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T10:33:38.674+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T10:33:38.682+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T10:33:38.682+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:33:38.682+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T10:33:38.682+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:33:38.693+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T10:33:38.701+0000] {standard_task_runner.py:55} INFO - Started process 3544 to run task
[2023-01-21T10:33:38.705+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmprr6t_k8_']
[2023-01-21T10:33:38.708+0000] {standard_task_runner.py:83} INFO - Job 199: Subtask transform_stage_generation
[2023-01-21T10:33:38.766+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host b3a2c4a96689
[2023-01-21T10:33:38.823+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T10:33:38.832+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T10:33:38.833+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T10:33:42.253+0000] {spark_submit.py:495} INFO - 23/01/21 10:33:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T10:33:42.550+0000] {spark_submit.py:495} INFO - 23/01/21 10:33:42 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T10:33:42.603+0000] {spark_submit.py:495} INFO - Exception in thread "main" java.io.IOException: Cannot run program "/usr/bin/python3.10": error=2, No such file or directory
[2023-01-21T10:33:42.603+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[2023-01-21T10:33:42.603+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[2023-01-21T10:33:42.603+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:97)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-21T10:33:42.604+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2023-01-21T10:33:42.605+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - Caused by: java.io.IOException: error=2, No such file or directory
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[2023-01-21T10:33:42.606+0000] {spark_submit.py:495} INFO - ... 15 more
[2023-01-21T10:33:42.615+0000] {spark_submit.py:495} INFO - 23/01/21 10:33:42 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T10:33:42.616+0000] {spark_submit.py:495} INFO - 23/01/21 10:33:42 INFO ShutdownHookManager: Deleting directory /tmp/spark-c8953341-f728-489f-b339-347323e6a9ab
[2023-01-21T10:33:42.678+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T10:33:42.683+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T103338, end_date=20230121T103342
[2023-01-21T10:33:42.694+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 199 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 3544)
[2023-01-21T10:33:42.725+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T10:33:42.745+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T11:21:19.319+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T11:21:19.338+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T11:21:19.338+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:19.339+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T11:21:19.339+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:19.368+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T11:21:19.390+0000] {standard_task_runner.py:55} INFO - Started process 482 to run task
[2023-01-21T11:21:19.403+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpnn7e3k7m']
[2023-01-21T11:21:19.410+0000] {standard_task_runner.py:83} INFO - Job 214: Subtask transform_stage_generation
[2023-01-21T11:21:19.573+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host b7c4de7fae0b
[2023-01-21T11:21:19.727+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T11:21:19.749+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T11:21:19.752+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T11:21:26.249+0000] {spark_submit.py:495} INFO - 23/01/21 11:21:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T11:21:27.429+0000] {spark_submit.py:495} INFO - 23/01/21 11:21:27 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T11:21:27.822+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-21T11:21:27.823+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 2, in <module>
[2023-01-21T11:21:27.823+0000] {spark_submit.py:495} INFO - from dotenv import load_dotenv
[2023-01-21T11:21:27.824+0000] {spark_submit.py:495} INFO - ModuleNotFoundError: No module named 'dotenv'
[2023-01-21T11:21:27.861+0000] {spark_submit.py:495} INFO - 23/01/21 11:21:27 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T11:21:27.865+0000] {spark_submit.py:495} INFO - 23/01/21 11:21:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-2e59c2d7-2be3-4c01-870e-f7313e0dd4e6
[2023-01-21T11:21:28.065+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T11:21:28.082+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T112119, end_date=20230121T112128
[2023-01-21T11:21:28.141+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 214 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 482)
[2023-01-21T11:21:28.221+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T11:21:28.291+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T11:46:37.268+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T11:46:37.278+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T11:46:37.278+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:46:37.278+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T11:46:37.279+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:46:37.290+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T11:46:37.298+0000] {standard_task_runner.py:55} INFO - Started process 2675 to run task
[2023-01-21T11:46:37.303+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpb8wieuxk']
[2023-01-21T11:46:37.307+0000] {standard_task_runner.py:83} INFO - Job 228: Subtask transform_stage_generation
[2023-01-21T11:46:37.382+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host b7c4de7fae0b
[2023-01-21T11:46:37.468+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T11:46:37.481+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T11:46:37.483+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T11:46:40.698+0000] {spark_submit.py:495} INFO - 23/01/21 11:46:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T11:46:40.930+0000] {spark_submit.py:495} INFO - 23/01/21 11:46:40 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T11:46:41.047+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-21T11:46:41.047+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 2, in <module>
[2023-01-21T11:46:41.047+0000] {spark_submit.py:495} INFO - from dotenv import load_dotenv, find_dotenv
[2023-01-21T11:46:41.048+0000] {spark_submit.py:495} INFO - ModuleNotFoundError: No module named 'dotenv'
[2023-01-21T11:46:41.060+0000] {spark_submit.py:495} INFO - 23/01/21 11:46:41 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T11:46:41.061+0000] {spark_submit.py:495} INFO - 23/01/21 11:46:41 INFO ShutdownHookManager: Deleting directory /tmp/spark-492b3bd3-74f8-408c-994d-7a65253736af
[2023-01-21T11:46:41.138+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T11:46:41.142+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T114637, end_date=20230121T114641
[2023-01-21T11:46:41.158+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 228 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 2675)
[2023-01-21T11:46:41.186+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T11:46:41.207+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T16:51:57.650+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T16:51:57.663+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T16:51:57.663+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T16:51:57.664+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T16:51:57.664+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T16:51:57.681+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T16:51:57.690+0000] {standard_task_runner.py:55} INFO - Started process 66 to run task
[2023-01-21T16:51:57.694+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp0972_flr']
[2023-01-21T16:51:57.697+0000] {standard_task_runner.py:83} INFO - Job 243: Subtask transform_stage_generation
[2023-01-21T16:51:57.780+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4260804338b2
[2023-01-21T16:51:57.879+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T16:51:57.892+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T16:51:57.896+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T16:52:05.070+0000] {spark_submit.py:495} INFO - 23/01/21 16:52:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T16:52:05.666+0000] {spark_submit.py:495} INFO - 23/01/21 16:52:05 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T16:52:05.942+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-21T16:52:05.942+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 2, in <module>
[2023-01-21T16:52:05.942+0000] {spark_submit.py:495} INFO - from dotenv import load_dotenv, find_dotenv
[2023-01-21T16:52:05.943+0000] {spark_submit.py:495} INFO - ModuleNotFoundError: No module named 'dotenv'
[2023-01-21T16:52:05.984+0000] {spark_submit.py:495} INFO - 23/01/21 16:52:05 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T16:52:05.987+0000] {spark_submit.py:495} INFO - 23/01/21 16:52:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-bc179021-6dd4-47ab-b1ad-e1f92cfc7d3d
[2023-01-21T16:52:06.150+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T16:52:06.159+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T165157, end_date=20230121T165206
[2023-01-21T16:52:06.181+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 243 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 66)
[2023-01-21T16:52:06.206+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T16:52:06.230+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T22:23:27.644+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T22:23:27.669+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-21T22:23:27.670+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T22:23:27.670+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-21T22:23:27.670+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T22:23:27.722+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-21T22:23:27.735+0000] {standard_task_runner.py:55} INFO - Started process 1382 to run task
[2023-01-21T22:23:27.739+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpxy9qfdox']
[2023-01-21T22:23:27.743+0000] {standard_task_runner.py:83} INFO - Job 252: Subtask transform_stage_generation
[2023-01-21T22:23:27.918+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4260804338b2
[2023-01-21T22:23:28.139+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-21T22:23:28.160+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-21T22:23:28.161+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-21T22:23:34.273+0000] {spark_submit.py:495} INFO - 23/01/21 22:23:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-21T22:23:34.518+0000] {spark_submit.py:495} INFO - 23/01/21 22:23:34 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-21T22:23:34.643+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-21T22:23:34.644+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 2, in <module>
[2023-01-21T22:23:34.645+0000] {spark_submit.py:495} INFO - from dotenv import load_dotenv, find_dotenv
[2023-01-21T22:23:34.646+0000] {spark_submit.py:495} INFO - ModuleNotFoundError: No module named 'dotenv'
[2023-01-21T22:23:34.673+0000] {spark_submit.py:495} INFO - 23/01/21 22:23:34 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T22:23:34.674+0000] {spark_submit.py:495} INFO - 23/01/21 22:23:34 INFO ShutdownHookManager: Deleting directory /tmp/spark-706075e9-14ac-4ec3-93b3-7235afb33693
[2023-01-21T22:23:34.809+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-21T22:23:34.812+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230121T222327, end_date=20230121T222334
[2023-01-21T22:23:34.825+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 252 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 1382)
[2023-01-21T22:23:34.860+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T22:23:34.883+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T00:08:32.465+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T00:08:32.527+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T00:08:32.528+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:08:32.529+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T00:08:32.533+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:08:32.586+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T00:08:32.604+0000] {standard_task_runner.py:55} INFO - Started process 73 to run task
[2023-01-22T00:08:32.614+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp1fxsxd7g']
[2023-01-22T00:08:32.620+0000] {standard_task_runner.py:83} INFO - Job 264: Subtask transform_stage_generation
[2023-01-22T00:08:32.760+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 669043c9475c
[2023-01-22T00:08:32.939+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T00:08:32.962+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T00:08:32.967+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T00:08:40.219+0000] {spark_submit.py:495} INFO - 23/01/22 00:08:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T00:08:40.683+0000] {spark_submit.py:495} INFO - 23/01/22 00:08:40 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-22T00:08:41.117+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T00:08:41.117+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 64, in <module>
[2023-01-22T00:08:41.118+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T00:08:41.118+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 16, in main
[2023-01-22T00:08:41.118+0000] {spark_submit.py:495} INFO - start_label = start.strftime("%Y%m%d%H%M")
[2023-01-22T00:08:41.118+0000] {spark_submit.py:495} INFO - AttributeError: 'str' object has no attribute 'strftime'
[2023-01-22T00:08:41.139+0000] {spark_submit.py:495} INFO - 23/01/22 00:08:41 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T00:08:41.140+0000] {spark_submit.py:495} INFO - 23/01/22 00:08:41 INFO ShutdownHookManager: Deleting directory /tmp/spark-120f195a-5458-4b9f-a8c9-2b170f2e23d0
[2023-01-22T00:08:41.243+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T00:08:41.250+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T000832, end_date=20230122T000841
[2023-01-22T00:08:41.273+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 264 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 73)
[2023-01-22T00:08:41.317+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T00:08:41.339+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T00:26:52.522+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T00:26:52.535+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T00:26:52.536+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:26:52.536+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T00:26:52.536+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:26:52.550+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T00:26:52.560+0000] {standard_task_runner.py:55} INFO - Started process 1753 to run task
[2023-01-22T00:26:52.564+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpwgi1e8q5']
[2023-01-22T00:26:52.567+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask transform_stage_generation
[2023-01-22T00:26:52.633+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 669043c9475c
[2023-01-22T00:26:52.697+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T00:26:52.707+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T00:26:52.708+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T00:26:55.233+0000] {spark_submit.py:495} INFO - 23/01/22 00:26:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T00:26:55.508+0000] {spark_submit.py:495} INFO - 23/01/22 00:26:55 WARN DependencyUtils: Local jar /opt/***/ /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-22T00:26:55.782+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T00:26:55.783+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 64, in <module>
[2023-01-22T00:26:55.783+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T00:26:55.783+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 16, in main
[2023-01-22T00:26:55.783+0000] {spark_submit.py:495} INFO - start_label = start.strftime("%Y%m%d%H%M")
[2023-01-22T00:26:55.783+0000] {spark_submit.py:495} INFO - AttributeError: 'str' object has no attribute 'strftime'
[2023-01-22T00:26:55.796+0000] {spark_submit.py:495} INFO - 23/01/22 00:26:55 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T00:26:55.797+0000] {spark_submit.py:495} INFO - 23/01/22 00:26:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-dcb2f355-ba1d-41b0-ba56-ec5c7e420c29
[2023-01-22T00:26:55.842+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T00:26:55.844+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T002652, end_date=20230122T002655
[2023-01-22T00:26:55.852+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 275 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /usr/local/spark/resources/gcs-connector-hadoop3-latest.jar, /usr/local/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 1753)
[2023-01-22T00:26:55.897+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T00:26:55.911+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T04:08:14.280+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T04:08:14.292+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T04:08:14.292+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:08:14.292+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T04:08:14.293+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:08:14.303+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T04:08:14.310+0000] {standard_task_runner.py:55} INFO - Started process 2142 to run task
[2023-01-22T04:08:14.315+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpipmlwo8o']
[2023-01-22T04:08:14.317+0000] {standard_task_runner.py:83} INFO - Job 287: Subtask transform_stage_generation
[2023-01-22T04:08:14.374+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host e3ae05c9a97e
[2023-01-22T04:08:14.432+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T04:08:14.440+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T04:08:14.441+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars /opt/***/spark/resources/gcs-connector-hadoop3-latest.jar, /opt/***/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T04:08:17.406+0000] {spark_submit.py:495} INFO - 23/01/22 04:08:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T04:08:17.641+0000] {spark_submit.py:495} INFO - 23/01/22 04:08:17 WARN DependencyUtils: Local jar /opt/***/ /opt/***/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-22T04:08:18.036+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T04:08:18.036+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 64, in <module>
[2023-01-22T04:08:18.036+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T04:08:18.037+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 16, in main
[2023-01-22T04:08:18.037+0000] {spark_submit.py:495} INFO - start_label = start.strftime("%Y%m%d%H%M")
[2023-01-22T04:08:18.037+0000] {spark_submit.py:495} INFO - AttributeError: 'str' object has no attribute 'strftime'
[2023-01-22T04:08:18.052+0000] {spark_submit.py:495} INFO - 23/01/22 04:08:18 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T04:08:18.053+0000] {spark_submit.py:495} INFO - 23/01/22 04:08:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-83f03f2b-5c0a-47d8-8ec6-4c81a4f164dc
[2023-01-22T04:08:18.120+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars /opt/***/spark/resources/gcs-connector-hadoop3-latest.jar, /opt/***/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T04:08:18.126+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T040814, end_date=20230122T040818
[2023-01-22T04:08:18.141+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 287 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars /opt/***/spark/resources/gcs-connector-hadoop3-latest.jar, /opt/***/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 2142)
[2023-01-22T04:08:18.196+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T04:08:18.214+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T04:38:40.765+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T04:38:40.782+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T04:38:40.783+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:38:40.783+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T04:38:40.784+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T04:38:40.810+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T04:38:40.820+0000] {standard_task_runner.py:55} INFO - Started process 487 to run task
[2023-01-22T04:38:40.829+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp15ljd7ph']
[2023-01-22T04:38:40.836+0000] {standard_task_runner.py:83} INFO - Job 298: Subtask transform_stage_generation
[2023-01-22T04:38:40.973+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 801017642f38
[2023-01-22T04:38:41.132+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T04:38:41.157+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T04:38:41.162+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar, spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T04:38:53.925+0000] {spark_submit.py:495} INFO - 23/01/22 04:38:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T04:38:54.682+0000] {spark_submit.py:495} INFO - 23/01/22 04:38:54 WARN DependencyUtils: Local jar /opt/***/gcs-connector-hadoop3-latest.jar does not exist, skipping.
[2023-01-22T04:38:54.683+0000] {spark_submit.py:495} INFO - 23/01/22 04:38:54 WARN DependencyUtils: Local jar /opt/***/ spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-22T04:38:55.456+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T04:38:55.457+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 64, in <module>
[2023-01-22T04:38:55.457+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T04:38:55.458+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 16, in main
[2023-01-22T04:38:55.458+0000] {spark_submit.py:495} INFO - start_label = start.strftime("%Y%m%d%H%M")
[2023-01-22T04:38:55.458+0000] {spark_submit.py:495} INFO - AttributeError: 'str' object has no attribute 'strftime'
[2023-01-22T04:38:55.519+0000] {spark_submit.py:495} INFO - 23/01/22 04:38:55 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T04:38:55.523+0000] {spark_submit.py:495} INFO - 23/01/22 04:38:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-db218fa9-59bd-4cb1-976a-6d4cafe914f6
[2023-01-22T04:38:55.665+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar, spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T04:38:55.676+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T043840, end_date=20230122T043855
[2023-01-22T04:38:55.776+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 298 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar, spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 487)
[2023-01-22T04:38:55.828+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T04:38:55.890+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T06:23:59.791+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T06:23:59.812+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T06:23:59.813+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T06:23:59.813+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T06:23:59.813+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T06:23:59.841+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T06:23:59.855+0000] {standard_task_runner.py:55} INFO - Started process 1113 to run task
[2023-01-22T06:23:59.865+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpqk0yihrm']
[2023-01-22T06:23:59.871+0000] {standard_task_runner.py:83} INFO - Job 310: Subtask transform_stage_generation
[2023-01-22T06:24:00.023+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host d68405340607
[2023-01-22T06:24:00.185+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T06:24:00.205+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T06:24:00.208+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T06:24:00.222+0000] {spark_submit.py:495} INFO - /home/***/.local/bin/spark-submit: line 27: /opt/spark/bin/spark-class: No such file or directory
[2023-01-22T06:24:00.245+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 127.
[2023-01-22T06:24:00.255+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T062359, end_date=20230122T062400
[2023-01-22T06:24:00.286+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 310 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 127.; 1113)
[2023-01-22T06:24:00.317+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T06:24:00.362+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T08:14:23.991+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T08:14:24.016+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T08:14:24.016+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T08:14:24.016+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T08:14:24.017+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T08:14:24.050+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T08:14:24.063+0000] {standard_task_runner.py:55} INFO - Started process 3811 to run task
[2023-01-22T08:14:24.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpsda5obe1']
[2023-01-22T08:14:24.078+0000] {standard_task_runner.py:83} INFO - Job 337: Subtask transform_stage_generation
[2023-01-22T08:14:24.255+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 16233a798013
[2023-01-22T08:14:24.445+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T08:14:24.470+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T08:14:24.477+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T08:14:34.630+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T08:14:35.261+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:35 WARN DependencyUtils: Local jar /opt/***/gcs-connector-hadoop3-latest.jar does not exist, skipping.
[2023-01-22T08:14:35.262+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:35 WARN DependencyUtils: Local jar /opt/***/spark-bigquery-with-dependencies_2.13-0.27.1.jar does not exist, skipping.
[2023-01-22T08:14:37.802+0000] {spark_submit.py:495} INFO - /opt/***/plugins/scripts/transform_raw_staging.py__DE_TENNET__total_generation__202101010000.json
[2023-01-22T08:14:37.972+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:37 INFO SparkContext: Running Spark version 3.3.1
[2023-01-22T08:14:38.039+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceUtils: ==============================================================
[2023-01-22T08:14:38.040+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceUtils: No custom resources configured for spark.driver.
[2023-01-22T08:14:38.041+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceUtils: ==============================================================
[2023-01-22T08:14:38.042+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SparkContext: Submitted application: gcp_playground
[2023-01-22T08:14:38.094+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2023-01-22T08:14:38.105+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceProfile: Limiting resource is cpu
[2023-01-22T08:14:38.107+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2023-01-22T08:14:38.267+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SecurityManager: Changing view acls to: ***
[2023-01-22T08:14:38.268+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SecurityManager: Changing modify acls to: ***
[2023-01-22T08:14:38.270+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SecurityManager: Changing view acls groups to:
[2023-01-22T08:14:38.271+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SecurityManager: Changing modify acls groups to:
[2023-01-22T08:14:38.273+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2023-01-22T08:14:39.400+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:39 INFO Utils: Successfully started service 'sparkDriver' on port 39549.
[2023-01-22T08:14:39.709+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:39 INFO SparkEnv: Registering MapOutputTracker
[2023-01-22T08:14:39.877+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:39 INFO SparkEnv: Registering BlockManagerMaster
[2023-01-22T08:14:40.019+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2023-01-22T08:14:40.022+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2023-01-22T08:14:40.041+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-01-22T08:14:40.161+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8cfa4ac0-21e9-4be9-8d88-c1a87b235f26
[2023-01-22T08:14:40.254+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2023-01-22T08:14:40.318+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO SparkEnv: Registering OutputCommitCoordinator
[2023-01-22T08:14:40.980+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:40 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2023-01-22T08:14:41.105+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO SparkContext: Added JAR /opt/spark/resources/gcs-connector-hadoop3-latest.jar at spark://16233a798013:39549/jars/gcs-connector-hadoop3-latest.jar with timestamp 1674375277959
[2023-01-22T08:14:41.108+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO SparkContext: Added JAR /opt/spark/resources/spark-bigquery-with-dependencies_2.13-0.27.1.jar at spark://16233a798013:39549/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar with timestamp 1674375277959
[2023-01-22T08:14:41.365+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO Executor: Starting executor ID driver on host 16233a798013
[2023-01-22T08:14:41.384+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2023-01-22T08:14:41.431+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO Executor: Fetching spark://16233a798013:39549/jars/gcs-connector-hadoop3-latest.jar with timestamp 1674375277959
[2023-01-22T08:14:41.600+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO TransportClientFactory: Successfully created connection to 16233a798013/192.168.32.7:39549 after 91 ms (0 ms spent in bootstraps)
[2023-01-22T08:14:41.632+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:41 INFO Utils: Fetching spark://16233a798013:39549/jars/gcs-connector-hadoop3-latest.jar to /tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d/userFiles-c7870333-0767-456c-a6ea-bb8cfc4effff/fetchFileTemp13076598969117327010.tmp
[2023-01-22T08:14:42.038+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO Executor: Adding file:/tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d/userFiles-c7870333-0767-456c-a6ea-bb8cfc4effff/gcs-connector-hadoop3-latest.jar to class loader
[2023-01-22T08:14:42.038+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO Executor: Fetching spark://16233a798013:39549/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar with timestamp 1674375277959
[2023-01-22T08:14:42.041+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO Utils: Fetching spark://16233a798013:39549/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar to /tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d/userFiles-c7870333-0767-456c-a6ea-bb8cfc4effff/fetchFileTemp1419589099040129525.tmp
[2023-01-22T08:14:42.410+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO Executor: Adding file:/tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d/userFiles-c7870333-0767-456c-a6ea-bb8cfc4effff/spark-bigquery-with-dependencies_2.13-0.27.1.jar to class loader
[2023-01-22T08:14:42.427+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33715.
[2023-01-22T08:14:42.428+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO NettyBlockTransferService: Server created on 16233a798013:33715
[2023-01-22T08:14:42.432+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2023-01-22T08:14:42.455+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 16233a798013, 33715, None)
[2023-01-22T08:14:42.464+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO BlockManagerMasterEndpoint: Registering block manager 16233a798013:33715 with 434.4 MiB RAM, BlockManagerId(driver, 16233a798013, 33715, None)
[2023-01-22T08:14:42.473+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 16233a798013, 33715, None)
[2023-01-22T08:14:42.479+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:42 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 16233a798013, 33715, None)
[2023-01-22T08:14:43.658+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:43 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2023-01-22T08:14:43.663+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:43 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2023-01-22T08:14:46.137+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: gs://entsoe_analytics_1009//opt/***/plugins/scripts/transform_raw_staging.py__DE_TENNET__total_generation__202101010000.json.
[2023-01-22T08:14:46.138+0000] {spark_submit.py:495} INFO - org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
[2023-01-22T08:14:46.138+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
[2023-01-22T08:14:46.139+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2023-01-22T08:14:46.139+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2023-01-22T08:14:46.139+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2023-01-22T08:14:46.140+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2023-01-22T08:14:46.141+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2023-01-22T08:14:46.141+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2023-01-22T08:14:46.141+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2023-01-22T08:14:46.142+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2023-01-22T08:14:46.142+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2023-01-22T08:14:46.143+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2023-01-22T08:14:46.143+0000] {spark_submit.py:495} INFO - at scala.Option.getOrElse(Option.scala:201)
[2023-01-22T08:14:46.143+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2023-01-22T08:14:46.144+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
[2023-01-22T08:14:46.144+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-22T08:14:46.145+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-22T08:14:46.145+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-22T08:14:46.146+0000] {spark_submit.py:495} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-22T08:14:46.146+0000] {spark_submit.py:495} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-01-22T08:14:46.146+0000] {spark_submit.py:495} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-01-22T08:14:46.147+0000] {spark_submit.py:495} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2023-01-22T08:14:46.147+0000] {spark_submit.py:495} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-01-22T08:14:46.148+0000] {spark_submit.py:495} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-01-22T08:14:46.148+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-01-22T08:14:46.149+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-01-22T08:14:46.149+0000] {spark_submit.py:495} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-01-22T08:14:46.198+0000] {spark_submit.py:495} INFO - Error, ada An error occurred while calling o38.load.
[2023-01-22T08:14:46.199+0000] {spark_submit.py:495} INFO - : org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
[2023-01-22T08:14:46.199+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
[2023-01-22T08:14:46.200+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2023-01-22T08:14:46.200+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2023-01-22T08:14:46.201+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2023-01-22T08:14:46.201+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2023-01-22T08:14:46.202+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2023-01-22T08:14:46.202+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2023-01-22T08:14:46.203+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2023-01-22T08:14:46.203+0000] {spark_submit.py:495} INFO - at scala.collection.immutable.List.map(List.scala:246)
[2023-01-22T08:14:46.204+0000] {spark_submit.py:495} INFO - at scala.collection.immutable.List.map(List.scala:79)
[2023-01-22T08:14:46.204+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2023-01-22T08:14:46.205+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2023-01-22T08:14:46.205+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2023-01-22T08:14:46.205+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2023-01-22T08:14:46.206+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2023-01-22T08:14:46.206+0000] {spark_submit.py:495} INFO - at scala.Option.getOrElse(Option.scala:201)
[2023-01-22T08:14:46.207+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2023-01-22T08:14:46.207+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
[2023-01-22T08:14:46.208+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-22T08:14:46.208+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-22T08:14:46.209+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-22T08:14:46.209+0000] {spark_submit.py:495} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-22T08:14:46.210+0000] {spark_submit.py:495} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-01-22T08:14:46.210+0000] {spark_submit.py:495} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-01-22T08:14:46.210+0000] {spark_submit.py:495} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2023-01-22T08:14:46.211+0000] {spark_submit.py:495} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-01-22T08:14:46.211+0000] {spark_submit.py:495} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-01-22T08:14:46.211+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-01-22T08:14:46.212+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-01-22T08:14:46.212+0000] {spark_submit.py:495} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-01-22T08:14:46.212+0000] {spark_submit.py:495} INFO - 
[2023-01-22T08:14:46.213+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T08:14:46.213+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 69, in <module>
[2023-01-22T08:14:46.213+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T08:14:46.213+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 56, in main
[2023-01-22T08:14:46.214+0000] {spark_submit.py:495} INFO - df_spark.write.format("bigquery").option("project", "rafzul-analytics-1009") \
[2023-01-22T08:14:46.214+0000] {spark_submit.py:495} INFO - UnboundLocalError: local variable 'df_spark' referenced before assignment
[2023-01-22T08:14:46.337+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO SparkContext: Invoking stop() from shutdown hook
[2023-01-22T08:14:46.368+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO SparkUI: Stopped Spark web UI at http://16233a798013:4040
[2023-01-22T08:14:46.401+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2023-01-22T08:14:46.434+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO MemoryStore: MemoryStore cleared
[2023-01-22T08:14:46.435+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO BlockManager: BlockManager stopped
[2023-01-22T08:14:46.457+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO BlockManagerMaster: BlockManagerMaster stopped
[2023-01-22T08:14:46.467+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2023-01-22T08:14:46.534+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO SparkContext: Successfully stopped SparkContext
[2023-01-22T08:14:46.535+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T08:14:46.535+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d
[2023-01-22T08:14:46.540+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-a84c50b3-3c1f-4a0e-a529-78af76b0d90d/pyspark-ae89b80a-7fbb-4cbb-9b07-1960fd09e3fb
[2023-01-22T08:14:46.590+0000] {spark_submit.py:495} INFO - 23/01/22 08:14:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-8a5e4f05-121b-4913-80b5-07596d0e8673
[2023-01-22T08:14:46.849+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T08:14:46.859+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T081423, end_date=20230122T081446
[2023-01-22T08:14:47.053+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 337 for task transform_stage_generation (Cannot execute: spark-submit --master local --jars gcs-connector-hadoop3-latest.jar,spark-bigquery-with-dependencies_2.13-0.27.1.jar --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 3811)
[2023-01-22T08:14:47.096+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T08:14:47.140+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-22T09:34:34.581+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T09:34:34.597+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-01-22T09:34:34.597+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T09:34:34.598+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-22T09:34:34.598+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T09:34:34.617+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): transform_stage_generation> on 2021-01-01 00:00:00+00:00
[2023-01-22T09:34:34.628+0000] {standard_task_runner.py:55} INFO - Started process 2744 to run task
[2023-01-22T09:34:34.634+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion-energydata', 'transform_stage_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmp8_xu1l25']
[2023-01-22T09:34:34.639+0000] {standard_task_runner.py:83} INFO - Job 396: Subtask transform_stage_generation
[2023-01-22T09:34:34.762+0000] {task_command.py:389} INFO - Running <TaskInstance: ingestion-energydata.transform_stage_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 266f60b86faa
[2023-01-22T09:34:34.934+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=ingestion-energydata
AIRFLOW_CTX_TASK_ID=transform_stage_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-01-22T09:34:34.954+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2023-01-22T09:34:34.957+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET
[2023-01-22T09:34:45.616+0000] {spark_submit.py:495} INFO - /opt/***/plugins/scripts/transform_raw_staging.py__DE_TENNET__total_generation__202101010000.json
[2023-01-22T09:34:45.829+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:45 INFO SparkContext: Running Spark version 3.3.1
[2023-01-22T09:34:46.014+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-01-22T09:34:46.280+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceUtils: ==============================================================
[2023-01-22T09:34:46.281+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceUtils: No custom resources configured for spark.driver.
[2023-01-22T09:34:46.281+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceUtils: ==============================================================
[2023-01-22T09:34:46.282+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SparkContext: Submitted application: gcp_playground
[2023-01-22T09:34:46.361+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2023-01-22T09:34:46.377+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceProfile: Limiting resource is cpu
[2023-01-22T09:34:46.380+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2023-01-22T09:34:46.538+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SecurityManager: Changing view acls to: ***
[2023-01-22T09:34:46.538+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SecurityManager: Changing modify acls to: ***
[2023-01-22T09:34:46.542+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SecurityManager: Changing view acls groups to:
[2023-01-22T09:34:46.543+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SecurityManager: Changing modify acls groups to:
[2023-01-22T09:34:46.545+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:46 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2023-01-22T09:34:47.317+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO Utils: Successfully started service 'sparkDriver' on port 36151.
[2023-01-22T09:34:47.410+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO SparkEnv: Registering MapOutputTracker
[2023-01-22T09:34:47.514+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO SparkEnv: Registering BlockManagerMaster
[2023-01-22T09:34:47.596+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2023-01-22T09:34:47.598+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2023-01-22T09:34:47.608+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-01-22T09:34:47.667+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6c3f0eea-0851-4af3-bc96-a56cc4c47a3b
[2023-01-22T09:34:47.716+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2023-01-22T09:34:47.765+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:47 INFO SparkEnv: Registering OutputCommitCoordinator
[2023-01-22T09:34:48.290+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2023-01-22T09:34:48.366+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO SparkContext: Added JAR /opt/spark/gcs-connector-hadoop3-latest.jar at spark://266f60b86faa:36151/jars/gcs-connector-hadoop3-latest.jar with timestamp 1674380085780
[2023-01-22T09:34:48.367+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO SparkContext: Added JAR /opt/spark/spark-bigquery-with-dependencies_2.13-0.27.1.jar at spark://266f60b86faa:36151/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar with timestamp 1674380085780
[2023-01-22T09:34:48.556+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO Executor: Starting executor ID driver on host 266f60b86faa
[2023-01-22T09:34:48.577+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2023-01-22T09:34:48.614+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO Executor: Fetching spark://266f60b86faa:36151/jars/gcs-connector-hadoop3-latest.jar with timestamp 1674380085780
[2023-01-22T09:34:48.788+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO TransportClientFactory: Successfully created connection to 266f60b86faa/192.168.64.4:36151 after 106 ms (0 ms spent in bootstraps)
[2023-01-22T09:34:48.806+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:48 INFO Utils: Fetching spark://266f60b86faa:36151/jars/gcs-connector-hadoop3-latest.jar to /tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca/userFiles-5bc2ac49-73f6-4943-88ae-ac8fcf641822/fetchFileTemp13931106110545614597.tmp
[2023-01-22T09:34:49.924+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:49 INFO Executor: Adding file:/tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca/userFiles-5bc2ac49-73f6-4943-88ae-ac8fcf641822/gcs-connector-hadoop3-latest.jar to class loader
[2023-01-22T09:34:49.926+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:49 INFO Executor: Fetching spark://266f60b86faa:36151/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar with timestamp 1674380085780
[2023-01-22T09:34:49.930+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:49 INFO Utils: Fetching spark://266f60b86faa:36151/jars/spark-bigquery-with-dependencies_2.13-0.27.1.jar to /tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca/userFiles-5bc2ac49-73f6-4943-88ae-ac8fcf641822/fetchFileTemp11642361368590390606.tmp
[2023-01-22T09:34:50.487+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO Executor: Adding file:/tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca/userFiles-5bc2ac49-73f6-4943-88ae-ac8fcf641822/spark-bigquery-with-dependencies_2.13-0.27.1.jar to class loader
[2023-01-22T09:34:50.530+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34891.
[2023-01-22T09:34:50.531+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO NettyBlockTransferService: Server created on 266f60b86faa:34891
[2023-01-22T09:34:50.541+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2023-01-22T09:34:50.580+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 266f60b86faa, 34891, None)
[2023-01-22T09:34:50.606+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO BlockManagerMasterEndpoint: Registering block manager 266f60b86faa:34891 with 434.4 MiB RAM, BlockManagerId(driver, 266f60b86faa, 34891, None)
[2023-01-22T09:34:50.622+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 266f60b86faa, 34891, None)
[2023-01-22T09:34:50.628+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:50 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 266f60b86faa, 34891, None)
[2023-01-22T09:34:52.040+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:52 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2023-01-22T09:34:52.059+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:52 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2023-01-22T09:34:53.931+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:53 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: gs://entsoe_analytics_1009//opt/***/plugins/scripts/transform_raw_staging.py__DE_TENNET__total_generation__202101010000.json.
[2023-01-22T09:34:53.931+0000] {spark_submit.py:495} INFO - org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
[2023-01-22T09:34:53.932+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
[2023-01-22T09:34:53.932+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2023-01-22T09:34:53.932+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2023-01-22T09:34:53.932+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2023-01-22T09:34:53.933+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2023-01-22T09:34:53.933+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2023-01-22T09:34:53.933+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2023-01-22T09:34:53.933+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2023-01-22T09:34:53.934+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2023-01-22T09:34:53.934+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2023-01-22T09:34:53.934+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2023-01-22T09:34:53.934+0000] {spark_submit.py:495} INFO - at scala.Option.getOrElse(Option.scala:201)
[2023-01-22T09:34:53.935+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2023-01-22T09:34:53.935+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
[2023-01-22T09:34:53.935+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-22T09:34:53.935+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-22T09:34:53.936+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-22T09:34:53.936+0000] {spark_submit.py:495} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-22T09:34:53.936+0000] {spark_submit.py:495} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-01-22T09:34:53.936+0000] {spark_submit.py:495} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-01-22T09:34:53.937+0000] {spark_submit.py:495} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2023-01-22T09:34:53.937+0000] {spark_submit.py:495} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-01-22T09:34:53.937+0000] {spark_submit.py:495} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-01-22T09:34:53.937+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-01-22T09:34:53.938+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-01-22T09:34:53.938+0000] {spark_submit.py:495} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-01-22T09:34:53.977+0000] {spark_submit.py:495} INFO - Error, ada An error occurred while calling o37.load.
[2023-01-22T09:34:53.977+0000] {spark_submit.py:495} INFO - : org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
[2023-01-22T09:34:53.978+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
[2023-01-22T09:34:53.978+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2023-01-22T09:34:53.979+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2023-01-22T09:34:53.979+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2023-01-22T09:34:53.980+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2023-01-22T09:34:53.980+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2023-01-22T09:34:53.980+0000] {spark_submit.py:495} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2023-01-22T09:34:53.981+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2023-01-22T09:34:53.981+0000] {spark_submit.py:495} INFO - at scala.collection.immutable.List.map(List.scala:246)
[2023-01-22T09:34:53.981+0000] {spark_submit.py:495} INFO - at scala.collection.immutable.List.map(List.scala:79)
[2023-01-22T09:34:53.982+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2023-01-22T09:34:53.982+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2023-01-22T09:34:53.982+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2023-01-22T09:34:53.983+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2023-01-22T09:34:53.983+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2023-01-22T09:34:53.983+0000] {spark_submit.py:495} INFO - at scala.Option.getOrElse(Option.scala:201)
[2023-01-22T09:34:53.983+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2023-01-22T09:34:53.984+0000] {spark_submit.py:495} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
[2023-01-22T09:34:53.984+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-22T09:34:53.984+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-22T09:34:53.984+0000] {spark_submit.py:495} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-22T09:34:53.985+0000] {spark_submit.py:495} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-22T09:34:53.985+0000] {spark_submit.py:495} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-01-22T09:34:53.985+0000] {spark_submit.py:495} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-01-22T09:34:53.985+0000] {spark_submit.py:495} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2023-01-22T09:34:53.986+0000] {spark_submit.py:495} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-01-22T09:34:53.986+0000] {spark_submit.py:495} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-01-22T09:34:53.986+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-01-22T09:34:53.986+0000] {spark_submit.py:495} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-01-22T09:34:53.987+0000] {spark_submit.py:495} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-01-22T09:34:53.987+0000] {spark_submit.py:495} INFO - 
[2023-01-22T09:34:53.987+0000] {spark_submit.py:495} INFO - Traceback (most recent call last):
[2023-01-22T09:34:53.987+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 68, in <module>
[2023-01-22T09:34:53.988+0000] {spark_submit.py:495} INFO - main(metrics_label=metrics_label, start=start, end=end, country_code=country_code)
[2023-01-22T09:34:53.988+0000] {spark_submit.py:495} INFO - File "/opt/***/plugins/scripts/transform_raw_staging.py", line 55, in main
[2023-01-22T09:34:53.988+0000] {spark_submit.py:495} INFO - df_spark.write.format("bigquery").option("project", "rafzul-analytics-1009") \
[2023-01-22T09:34:53.988+0000] {spark_submit.py:495} INFO - UnboundLocalError: local variable 'df_spark' referenced before assignment
[2023-01-22T09:34:54.087+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO SparkContext: Invoking stop() from shutdown hook
[2023-01-22T09:34:54.114+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO SparkUI: Stopped Spark web UI at http://266f60b86faa:4040
[2023-01-22T09:34:54.143+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2023-01-22T09:34:54.167+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO MemoryStore: MemoryStore cleared
[2023-01-22T09:34:54.168+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO BlockManager: BlockManager stopped
[2023-01-22T09:34:54.181+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO BlockManagerMaster: BlockManagerMaster stopped
[2023-01-22T09:34:54.187+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2023-01-22T09:34:54.219+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO SparkContext: Successfully stopped SparkContext
[2023-01-22T09:34:54.220+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO ShutdownHookManager: Shutdown hook called
[2023-01-22T09:34:54.222+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca
[2023-01-22T09:34:54.231+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-380e9f3e-cbbb-4b70-a418-18e0abbec676
[2023-01-22T09:34:54.239+0000] {spark_submit.py:495} INFO - 23/01/22 09:34:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-fcdaf70c-1ab2-4781-8476-61a07bdccaca/pyspark-7e74380f-4fd3-4c75-94ca-f42831efcc3f
[2023-01-22T09:34:54.373+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.
[2023-01-22T09:34:54.384+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=ingestion-energydata, task_id=transform_stage_generation, execution_date=20210101T000000, start_date=20230122T093434, end_date=20230122T093454
[2023-01-22T09:34:54.411+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 396 for task transform_stage_generation (Cannot execute: spark-submit --master local --name arrow-spark /opt/***/plugins/scripts/transform_raw_staging.py total_generation 202101010000 202101010100 DE_TENNET. Error code is: 1.; 2744)
[2023-01-22T09:34:54.450+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-22T09:34:54.476+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
